name: Graphs CI
on:
  schedule:
    - cron: "0 1 * * *"
  repository_dispatch:
    types: [graphs]
  workflow_dispatch:
jobs:
  release:
    name: Generate graphs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Auth git com GH_PAT
        run: git remote set-url origin "https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git"
      - name: Update graphs
        uses: upptime/uptime-monitor@master
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
