name: Summary CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [summary]
  workflow_dispatch:
jobs:
  release:
    name: Generate README summary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update summary in README
        uses: upptime/uptime-monitor@master
        with:
          command: "summary"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
